function list = getListGroundObjects

list = {'floor', 'ground', 'grass', 'field', 'street', 'road', ...
          'sidewalk', 'path', 'sea', 'water', 'sand', 'carpet', 'beach', 'highway', ...
          'lake', 'pond', 'ocean', 'river', 'snow'};
